version: 2
updates:
  # Maintain dependencies for GitHub Actions in the root
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain pip dependencies (including those in environment.yaml)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pip-dependencies:
        patterns:
          - "*"

  # Maintain conda dependencies (in environment.yaml)
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      conda-dependencies:
        patterns:
          - "*"
