name: template
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.13.11=hc7d8306_100_cp313
  - python_abi=3.13=3_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - arrow==1.4.0
      - binaryornot==0.4.4
      - certifi==2026.1.4
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cookiecutter==2.6.0
      - idna==3.11
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - six==1.17.0
      - text-unidecode==1.3
      - tzdata==2025.3
      - urllib3==2.6.3
      - uv==0.9.26
