blank_issues_enabled: true
contact_links:
  - name: Questions / usage help
    url: https://github.com/jtzanetatos/cookiecutter-ml-project/discussions
    about: Ask questions here instead of opening an issue.