name: Release PR (Commitizen)

on:
  push:
    branches: [main]
    paths-ignore:
      - "CHANGELOG.md"
      - "pyproject.toml"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-pr:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version + changelog (no push)
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
          changelog_increment_filename: body.md

      - name: Create/Update PR
        uses: peter-evans/create-pull-request@v8
        with:
          branch: release/commitizen-bump
          title: "bump: version ${{ steps.cz.outputs.previous_version }} â†’ ${{ steps.cz.outputs.version }}"
          body-path: body.md
          # Prevent body.md from being committed
          add-paths: |
            pyproject.toml
            CHANGELOG.md